SELECT C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES*B.PRICE) AS TOTAL_SALES FROM BOOK_SALES A
LEFT JOIN BOOK B ON B.BOOK_ID = A.BOOK_ID
LEFT JOIN AUTHOR C ON C.AUTHOR_ID = B.AUTHOR_ID
WHERE A.SALES_DATE LIKE "2022-01%"
GROUP BY B.CATEGORY, B.AUTHOR_ID
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC