SELECT A.FLAVOR FROM (SELECT FLAVOR, SUM(TOTAL_ORDER) AS ORDERS FROM FIRST_HALF GROUP BY FLAVOR) A
LEFT JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS ORDERS FROM JULY GROUP BY FLAVOR) B ON A.FLAVOR = B.FLAVOR
ORDER BY (A.ORDERS + B.ORDERS) DESC LIMIT 3