SELECT A.USER_ID, A.PRODUCT_ID FROM ONLINE_SALE A LEFT JOIN (SELECT PRODUCT_ID, COUNT(PRODUCT_ID) AS NUM FROM ONLINE_SALE GROUP BY PRODUCT_ID) B
ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.NUM >= 2
ORDER BY A.USER_ID ASC, PRODUCT_ID DESC


SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) >= 2
ORDER BY USER_ID, PRODUCT_ID DESC;