SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(B.SCORE, 2) AS SCORE FROM REST_INFO A
LEFT JOIN (SELECT REST_ID, AVG(REVIEW_SCORE) AS SCORE FROM REST_REVIEW GROUP BY REST_ID) B ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE "서울%" AND SCORE IS NOT NULL
ORDER BY SCORE DESC, FAVORITES DESC